version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered prebuild phase
  build:
    commands:
      - echo Build started on 
      - mvn  -DskipTests clean package  
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/stengameserver-0.0.1-SNAPSHOT.jar
  discard-paths: yes
